---
# tasks file for aws-instance


- name: Provision AWS instance
  ec2:
    state: "{{ state }}"
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_image }}"
    wait: yes
    wait_timeout: 500
    exact_count: 1
    count_tag:
      Name: "{{ instance_name }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: "{{ public_ip }}"
    group: "{{ security_group }}"
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
