---
# tasks file for cfme-ose-setup


- name: Get Openshift token
  command: oc sa get-token -n management-infra management-admin
  register: token

- debug: var=token.stdout

- name: Set token as an Openshift fact
  set_fact:
    token: "{{ token.stdout }}"
    
- name: Sleep for 3 minutes to allow instance to come up
  command: sleep 180
